{{- if or (and .Values.global.JWTSecret .Values.global.secretNameOverride) (and (not .Values.global.JWTSecret) (not .Values.global.secretNameOverride)) }}
{{- fail ".Values.global.JWTSecret or .Values.global.secretNameOverride is required" }}
{{- end }}
